server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;

    location = /demo_webpage {
        return 301 /demo_webpage/;
    }

    location /demo_webpage/ {
        rewrite ^/demo_webpage/(.*)$ /$1 break;
        try_files $uri $uri/ /index.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
